theme: jekyll-theme-minimal
title: Minfei Fei
# Education
## University of Cambridge
Ph.D., Materials Science and Metallurgy
## Rice University
Academic Visitor, Materials Science and NanoEngineering
Master, Materials Science and NanoEngineering, Rice University
## Nanjing University
B.Eng. with Outstanding Grauduate Award, New Energy Science and Engineering
## Pacific Northwest National Laboratory
Undergraduate Visiting Researcher
